name = "Create: FlyByWire"
author = "Misha Artemiev"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a783386ce4654f5e01628847a93a4b3f4c4d99029d62b11cc2bda90d9bba9050"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
