name = "Create: FlyByWire"
author = "Misha Artemiev"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d769616b78ea026c5e5cfcf8ccb2564e4fd7efd50f72caf419c1fc30f2b124ad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
