name = "Create: FlyByWire"
author = "Misha Artemiev"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0229f059c946bcddeebafa592c3dcebf716fc7b3047a068763d12d51b1f5ebdf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
