name = "Create: FlyByWire"
author = "Misha Artemiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "901cc4af7edc789fcd54be5c215e9385c60d2492ca2391621ff5284d63e49347"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
