name = "Create: FlyByWire"
author = "Misha Artemiev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e84a149bcd6bc73ffce62d7ef7fc9aec70b9d9ae3bc1f8b735ec3ff0d5b72182"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
